// Code generated by Rigger DO NOT EDIT
package funcs

import (
	"html/template"
)

var FuncMap = map[string]interface{}{

	"Strong": //自定义模版函数
	func(text string) template.HTML {
		return template.HTML("<strong>" + text + "<strong>")
	},

	"Test": func() string {
		return "TEST"
	},
}
